version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
